puts 'Tipes de alimentacion '
Tipe.create( name: 'Hidratación canina' , description: 'beber suficiente agua a lo largo del día, por lo que su recipiente siempre debe tener de sobra. Esta agua debe ser potable, fresca y renovada diariamente. El perro deberá poder beber libremente, siempre que lo desee. El consumo medio diario de agua es de 60 ml por kilo de peso.', category_id: @Categorie2.id )
Tipe.create( name: 'Comidas regulares' , description: 'comer cada día en el mismo lugar, a la misma hora y en el mismo recipiente, el mismo alimento.', category_id: @Categorie2.id )
Tipe.create( name: 'Elige bien el alimento' , description: 'La calidad del alimento no es algo trivial. Ante todo deberán primar los criterios de equilibrio nutritivo. Tres criterios fundamentales intervienen en la elección del buen alimento para un perro: su edad, su nivel de actividad física o fisiológica y su tamaño.', category_id: @Categorie2.id )
Tipe.create( name: 'Higiene excepcional' , description: 'los alimentos industriales ofrecen las mejores garantías de salubridad higiénica. Bien utilizados, no presentan ningún riesgo de intoxicación alimenticia. Cuidado con las cajas empezadas.', category_id: @Categorie2.id )
Tipe.create( name: 'Atención a las transiciones alimentarias' , description: 'Cualquier modificación alimentaria debe hacerse progresivamente (aproximadamente una semana), para permitir al perro adaptarse (gustativa, digestiva y metabólicamente) y para dejar tiempo a su microflora intestinal a reconstituirse específicamente para digerir el nuevo alimento.', category_id: @Categorie2.id )
Tipe.create( name: 'Cuida las cantidades de alimento' , description: 'Calcúlala teniendo en cuenta la necesidad energética diaria del perro y el contenido energético y calórico de los alimentos. Si pesas el alimento diariamente, evitarás cualquier derivación progresiva hacia la obesidad.', category_id: @Categorie2.id )

puts 'Tipes de salud '
Tipe.create( name: 'Evita cargarlo constantemente' , description: 'Trata de resistir esta tentación, porque su cuerpo es muy delicado. Si lo haces, primero coloca una mano sobre su parte posterior y otra bajo el pecho, levántalo con ambas manos y mantenlo junto a tu cuerpo para que se sienta seguro.', category_id: @Categorie3.id )
Tipe.create( name: 'Horario para sus necesidades' , description: 'Establece una rutina regular de alimentación; si se trata de un perro, sácalo de paseo con frecuencia para que haga sus necesidades, especialmente cuando se despierte.', category_id: @Categorie3.id )
Tipe.create( name: 'Cuida su higiene:' , description: 'El cepillado regular es esencial para los perros jóvenes, debido a que elimina el pelo muerto, la suciedad y los parásitos; además, estimula el aporte de sangre hacia la piel, lo que genera un pelaje de aspecto más sano y brillante.', category_id: @Categorie3.id )
Tipe.create( name: 'Supervisa su dentición y masticación: ' , description: 'Para ayudar a que salgan todos los dientes y deje de morder los muebles, tu cachorro necesitará algún objeto indestructible como puede ser un hueso de goma o una pelota para masticar. ', category_id: @Categorie3.id )
Tipe.create( name: 'Una correcta atención sanitaria' , description: 'En el caso de los cachorros, ellos son susceptibles a cualquier enfermedad contagiosa, por lo que es aconsejable realizar una visita temprana al veterinario. Las primeras vacunas se administrarán ya a las 6-8 semanas de', category_id: @Categorie3.id )
Tipe.create( name: 'Dieta y ejercicio' , description: 'Son vitales para el bienestar de tu mascota, sobre todo si se trata de un perro o un gato. Al ser muy juguetones y enérgicos, debes asegurarte de que realizan el ejercicio adecuado. ', category_id: @Categorie3.id )
